extends:
  - eslint:recommended
  - google
  - plugin:wc/recommended
  - plugin:n/recommended
globals:
  goog: false
  assert: false
env:
  jasmine: true
  browser: true
  es6: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - wc
parserOptions:
  ecmaVersion: 2020
  sourceType: module
settings:
  wc:
    elementBaseClasses: [ "BaseElement", "LitElement", "FormElement" ]
rules:
  # Rules temporally disabled
  "@typescript-eslint/explicit-function-return-type": off

  # Rules disabled in favor of clang-format
  "@typescript-eslint/indent": off
  indent: off
  max-len: off
  block-spacing: off

  "@typescript-eslint/explicit-member-accessibility": [ error, { "accessibility": "no-public" } ]

  no-new: warn
  quotes: [ error, single, { "avoidEscape": true } ]
  no-var: error
  no-floating-decimal: error
  no-unused-vars:
    - error
    # Account for closure compiler conventions. See docs/closure-compiler.md
    # Ignores: MDC[PascalCase]Adapter (records), [PascalCase]Type (typedefs)
    - varsIgnorePattern: ^(?:(?:MDC(?:(?:[A-Z][a-z0-9]+)+)Adapter)|(?:(?:(?:[A-Z][a-z0-9]+)+)Type))$

  # TODO: Enable once https://github.com/material-components/material-components-web/milestone/4
  # is complete
  require-jsdoc: off
  valid-jsdoc: off

  prefer-const: error
  comma-dangle: off
  'n/no-missing-import': warn
overrides:
  - files: [ "**/*.ts" ]
    rules:
      no-unused-vars: off
      no-invalid-this: off
      new-cap: off
  - files: [ "**/test/*.ts" ]
    rules:
      "@typescript-eslint/no-non-null-assertion": off
