name: Build Catalog

on: [ push ]

jobs:
  build-catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: ${{ !env.ACT && 'pnpm' || '' }}
      - uses: google/wireit@setup-github-actions-caching/v1
      - run: pnpm install
      - run: pnpm build:catalog
        env:
          WIREIT_FAILURES: continue
