name: Update API Docs

on:
  push:
    branches: [main, catalog]
  workflow_dispatch:
  # allows triggering from the gihub UI
jobs:
  check-for-doc-changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: ${{ !env.ACT && 'pnpm' || '' }}
      - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install Dependencies
        run: pnpm install

      - name: Update Docs
        run: pnpm update-docs

      - name: Check if update-docs produces git diff
        id: ifChange
        run: git diff --exit-code || echo "::set-output name=changed::yes"

      - name: Create PR
        if: steps.ifChange.outputs.changed == 'yes'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.LIT_ROBOT_ACCESS_TOKEN }}
          commit-message: 'docs: update API docs'
          author: lit-robot <lit-robot@google.com>
          committer: lit-robot <lit-robot@google.com>
          title: 'docs: update API docs'
          body: This PR was auto generated by the update-docs-on-main GitHub action.
          reviewers: maicol07
          branch: auto-update-docs
